### ISSUE TITLE
스팸 차단 실패 사례

### ISSUE THREAD

**Issue by Lastorder-DC** [nulta/fedi_findandkillspam#2]
[실패사례.zip](https://github.com/nulta/fedi_findandkillspam/files/14332061/default.zip)
위 이미지가 들어간 툿이 차단되지 않는걸 확인했습니다

![image](https://github.com/nulta/fedi_findandkillspam/assets/18280396/869e6bc2-600c-40cb-acf8-373d311d8002)

**Comment by nulta** [comment]
확인 중입니다...

**Comment by nulta** [comment]
Rev9에서 고쳐졌을 겁니다.
